"use client";

import React, { useState } from "react";
import {
  X,
  Smartphone,
  Tablet,
  Monitor,
  Download,
  Printer,
  ZoomIn,
  ZoomOut,
  ChevronLeft,
  ChevronRight,
  ShieldCheck,
  FileText,
  FileSpreadsheet,
  FileCode,
  CheckCircle2,
  Lock,
  Calendar,
  User,
  Hash,
  Share2,
  Sparkles,
  Activity,
  AlertCircle,
  Presentation,
} from "lucide-react";

export interface PreviewDocument {
  id: string;
  filename: string;
  type: "pdf" | "doc" | "sheet" | "code" | "txt" | "pptx";
  title: string;
  author: string;
  department: string;
  date: string;
  size: string;
  hash: string;
  pages: {
    pageNumber: number;
    title: string;
    sections: {
      heading?: string;
      content: string;
      table?: { headers: string[]; rows: string[][] };
      callout?: { type: "info" | "warning" | "success"; text: string };
    }[];
  }[];
}

interface DocumentPreviewModalProps {
  document: PreviewDocument | null;
  isOpen: boolean;
  onClose: () => void;
  onDownload?: (doc: PreviewDocument) => void;
}

export const SAMPLE_DOCUMENTS: Record<string, PreviewDocument> = {
  defense_audit: {
    id: "doc-def-001",
    filename: "Defense_Contract_Compliance_Audit_2026.pdf",
    type: "pdf",
    title: "Air-Gapped Sovereign Compliance & Export Control Audit",
    author: "L4 Sovereign Officer (user-001)",
    department: "Defense Engineering & Infosec",
    date: "September 13, 2026",
    size: "2.4 MB",
    hash: "sha256-8f4b7a9c3e2d1f0e4b8a7c6d5e3f2a1b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f",
    pages: [
      {
        pageNumber: 1,
        title: "Executive Summary & Air-Gap Perimeter Verification",
        sections: [
          {
            heading: "1. Scope of Air-Gapped Assessment",
            content:
              "This audit report certifies that the AstraSovereign on-premise execution environment operates under complete physical and logical isolation. No packets have egressed beyond the 127.0.0.1 loopback interface during the entire model inference lifecycle.",
            callout: {
              type: "success",
              text: "AIR-GAP CERTIFICATION: Zero telemetry egress packets detected across all active worker threads and PCIe NVLink buses.",
            },
          },
          {
            heading: "2. Evaluated Technical Schematics & Vendor Agreements",
            content:
              "Cross-verification of 14 vendor agreements was executed locally using the Qwen 2.5 Coder and Llama 3.3 quantized models. Key contractual constraints and ITAR regulatory clauses were verified without external cloud API dependencies.",
            table: {
              headers: ["Vendor ID", "Agreement Type", "ITAR Scope", "Clearance Status"],
              rows: [
                ["VND-4891", "Titanium Alloy Supply", "Category VIII(a)", "Approved (L4)"],
                ["VND-5012", "Cryogenic Sensor Array", "Category XII(c)", "Approved (L4)"],
                ["VND-5144", "Secure Bus Controller", "Category XI(b)", "Pending Sign-off"],
                ["VND-5289", "Optical Lens Assembly", "Category XIII(e)", "Approved (L4)"],
              ],
            },
          },
        ],
      },
      {
        pageNumber: 2,
        title: "Risk Analysis & Cryptographic Integrity Ledger",
        sections: [
          {
            heading: "3. Cryptographic Verification & Tamper Evidence",
            content:
              "Every deliverable generated by AstraSovereign is signed with a localized SHA-256 HMAC digest stored in a tamper-evident on-premise SQLite ledger. Any unauthorized byte alteration invalidates the cryptographic stamp.",
            callout: {
              type: "info",
              text: "LEDGER STATUS: Cryptographic hash chain verified from Genesis Block #0 to current Block #8492.",
            },
          },
          {
            heading: "4. Officer Recommendation & Next Steps",
            content:
              "1. Maintain strict loopback firewall iptables configuration.\n2. Proceed with production shipment for approved vendors.\n3. Escalate VND-5144 to Defense Legal Review for final clearance block.",
          },
        ],
      },
    ],
  },
  inspection_report: {
    id: "doc-insp-002",
    filename: "Turbine_Inspection_Maintenance_Report.docx",
    type: "doc",
    title: "High-Pressure Turbine Inspection & Clearance Note",
    author: "Senior Mechanical Analyst (user-002)",
    department: "Operations & Mechanical Reliability",
    date: "September 12, 2026",
    size: "1.8 MB",
    hash: "sha256-a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0",
    pages: [
      {
        pageNumber: 1,
        title: "Inspection Findings & Clearance Status",
        sections: [
          {
            heading: "Inspection Overview",
            content:
              "Non-destructive ultrasonic testing was completed on High-Pressure Turbine Stage 2 blades. Dimensional variance remained within ±0.012 mm of manufacturing specifications.",
            callout: {
              type: "success",
              text: "TOLERANCE CHECK: All 48 rotor blades passed magnetic particle inspection without surface micro-fractures.",
            },
          },
          {
            heading: "Flow Velocity & Pressure Loss Data",
            content:
              "Pressure drop calculation was verified in the local Python Docker sandbox using the Darcy-Weisbach formulation.",
            table: {
              headers: ["Stage", "Inlet Pressure (bar)", "Outlet Pressure (bar)", "Delta (kPa)"],
              rows: [
                ["Stage 1", "42.5", "38.2", "430 kPa"],
                ["Stage 2", "38.2", "33.8", "440 kPa"],
                ["Stage 3", "33.8", "29.1", "470 kPa"],
              ],
            },
          },
        ],
      },
    ],
  },
  ocr_ledger: {
    id: "doc-ocr-003",
    filename: "Procurement_Ledger_RapidOCR_Extract.xlsx",
    type: "sheet",
    title: "Extracted Tabular Procurement Ledger",
    author: "RapidOCR Local Extraction Agent",
    department: "Finance & Supply Chain",
    date: "September 13, 2026",
    size: "640 KB",
    hash: "sha256-f0e1d2c3b4a5968778695a4b3c2d1e0ff0e1d2c3b4a5968778695a4b3c2d1e0f",
    pages: [
      {
        pageNumber: 1,
        title: "Extracted Ledger Table",
        sections: [
          {
            heading: "OCR Ingestion Results (18 Scanned Invoices)",
            content:
              "18 scanned physical procurement invoices were processed by RapidOCR locally on PCIe GPU. Character confidence rate: 99.7%.",
            table: {
              headers: ["Invoice #", "Vendor", "Date", "Items", "Total Amount ($)"],
              rows: [
                ["INV-98210", "AeroPrecision Metals", "2026-09-02", "Grade 5 Titanium Bar", "$148,200.00"],
                ["INV-98211", "CryoSensors Inc", "2026-09-04", "PT-100 RTD Probes (x40)", "$24,800.00"],
                ["INV-98212", "OmniShield Composites", "2026-09-08", "Carbon Fiber Prepreg", "$92,400.00"],
                ["INV-98213", "Vortex Fluidics", "2026-09-10", "High-Flow Control Valve", "$36,150.00"],
                ["INV-98214", "Hardened Microchips", "2026-09-11", "FPGA Radiation Hardened", "$210,000.00"],
              ],
            },
          },
        ],
      },
    ],
  },
  brief_q3: {
    id: "doc-brief-004",
    filename: "Exec_Brief_Q3.pptx",
    type: "pptx",
    title: "Q3 Sovereign Autonomous Operations & Strategic Briefing",
    author: "L4 Sovereign Directorate (user-001)",
    department: "Strategic Initiatives & Air-Gap Defense",
    date: "September 13, 2026",
    size: "4.2 MB",
    hash: "sha256-e9c8b7a6f5e4d3c2b1a0987654321fedcba0987654321fedcba0987654321fed",
    pages: [
      {
        pageNumber: 1,
        title: "Slide 1: Executive Overview & Physical Air-Gap Boundary",
        sections: [
          {
            heading: "Strategic Summary & Air-Gap Invariant",
            content:
              "AstraSovereign Q3 operations achieved 100% air-gapped autonomy across all localized neural models, executing 2,400+ inference workflows with 0 bytes outbound egress across loopback 127.0.0.1 and NVLink interconnects.",
            callout: {
              type: "success",
              text: "PERIMETER STATUS: Zero cloud dependencies, zero external telemetry egress packets recorded.",
            },
          },
          {
            heading: "Key Operational Workload Telemetry",
            content: "Verified local inference metrics across active model pillars:",
            table: {
              headers: ["Workload Pillar", "Active Model", "Inference TTFT", "Clearance Status"],
              rows: [
                ["Defense RAG", "Qwen 2.5 32B", "11.4 ms", "ITAR Level 4 Approved"],
                ["Code Synthesizer", "Qwen 2.5 Coder", "14.2 ms", "Docker Sandbox Verified"],
                ["Reasoning Engine", "DeepSeek R1", "18.8 ms", "Air-Gapped Loopback"],
                ["Executive Brief", "Llama 3.3 70B", "16.1 ms", "SHA-256 Ledger Signed"],
              ],
            },
          },
        ],
      },
      {
        pageNumber: 2,
        title: "Slide 2: High-Pressure NVLink Model Inference Telemetry",
        sections: [
          {
            heading: "Hardware Throughput & VRAM Utilization",
            content:
              "Local NVIDIA RTX 4090 / H100 PCIe Gen4 bus sustained 74.2 tokens/second peak throughput under concurrent multi-agent task execution without thermal throttling. Memory allocation stabilized at 18.4 GB of 24.0 GB total capacity.",
            callout: {
              type: "info",
              text: "HARDWARE TELEMETRY: Thermal core temperature 52°C, PCIe Gen4 x16 link width operating at full bandwidth.",
            },
          },
        ],
      },
      {
        pageNumber: 3,
        title: "Slide 3: Zero-Egress Deliverable Verification & Q4 Roadmap",
        sections: [
          {
            heading: "Cryptographic Deliverables Integrity",
            content:
              "All generated PowerPoint decks (.pptx), Word reports (.docx), and Excel sheets are signed with tamper-evident HMAC digests verified against the sovereign local ledger before distribution.",
            callout: {
              type: "success",
              text: "DELIVERABLES SEAL: 100% Cryptographic Verification Rate across all 48 Q3 output packages.",
            },
          },
        ],
      },
    ],
  },
  telemetry_audit: {
    id: "doc-audit-005",
    filename: "Telemetry_Audit.docx",
    type: "doc",
    title: "Zero-Egress Telemetry & Hardware Loopback Isolation Audit",
    author: "Lead Security Auditor (user-001)",
    department: "Cryptographic Security & System Integrity",
    date: "September 13, 2026",
    size: "1.9 MB",
    hash: "sha256-7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b",
    pages: [
      {
        pageNumber: 1,
        title: "Section 1: Hardware Socket Isolation & Loopback Analysis",
        sections: [
          {
            heading: "1. Loopback Invariant Verification (127.0.0.1)",
            content:
              "Automated kernel-level iptables audit confirmed that all AI runtime processes (Ollama, Docker Sandbox, RapidOCR) were strictly bound to 127.0.0.1. Zero socket connections were initiated to external public IP addresses.",
            callout: {
              type: "success",
              text: "VERIFIED ZERO-EGRESS: Netstat & tcpdump logs confirm 0 outbound packets over 96 continuous hours.",
            },
          },
          {
            heading: "2. PCIe Bus Telemetry Verification",
            content:
              "PCIe Gen4 x16 bus traffic was monitored using hardware perf counters. All memory transactions occurred strictly between system DDR5 RAM and GPU VRAM.",
            table: {
              headers: ["Interface", "Binding Address", "Dropped Packets", "Integrity State"],
              rows: [
                ["lo0", "127.0.0.1:11434", "0 dropped (Clean)", "Passed 100%"],
                ["docker0", "172.17.0.1 (Isolated)", "0 dropped (Clean)", "Passed 100%"],
                ["eth0", "Disabled / Unplugged", "All dropped", "Air-Gapped"],
                ["wlan0", "Disabled / RF-Killed", "All dropped", "Air-Gapped"],
              ],
            },
          },
        ],
      },
      {
        pageNumber: 2,
        title: "Section 2: Cryptographic Audit Signature & Directorate Sign-Off",
        sections: [
          {
            heading: "3. Tamper-Evident Ledger Integrity Stamp",
            content:
              "This Telemetry Audit Document has been signed with SHA-256 digest 7a8b9c0d1e2f3a4b... and committed to Genesis Block #8493 in the on-premise local ledger.",
            callout: {
              type: "info",
              text: "COMPLIANCE LEVEL: NIST SP 800-171 & ISO/IEC 27001 Air-Gap Isolation criteria fully satisfied.",
            },
          },
        ],
      },
    ],
  },
};

// Aliases for seamless filename-based or slug-based lookups
SAMPLE_DOCUMENTS["Exec_Brief_Q3.pptx"] = SAMPLE_DOCUMENTS.brief_q3;
SAMPLE_DOCUMENTS["Brief_Q3.pptx"] = SAMPLE_DOCUMENTS.brief_q3;
SAMPLE_DOCUMENTS["ef_Q3.pptx"] = SAMPLE_DOCUMENTS.brief_q3;
SAMPLE_DOCUMENTS["Telemetry_Audit.docx"] = SAMPLE_DOCUMENTS.telemetry_audit;

export default function DocumentPreviewModal({
  document,
  isOpen,
  onClose,
  onDownload,
}: DocumentPreviewModalProps) {
  const [deviceMode, setDeviceMode] = useState<"desktop" | "phone" | "tablet">("desktop");
  const [currentPage, setCurrentPage] = useState(1);
  const [zoomLevel, setZoomLevel] = useState(100);

  if (!isOpen || !document) return null;

  const activeDoc = document;
  const totalPages = activeDoc.pages.length || 1;
  const activePageData = activeDoc.pages[currentPage - 1] || activeDoc.pages[0];

  const handleZoom = (delta: number) => {
    setZoomLevel((prev) => Math.min(Math.max(prev + delta, 60), 160));
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm p-3 sm:p-6 animate-in fade-in select-none">
      <div className="relative w-full max-w-6xl h-[92vh] bg-[#0d0d12] rounded-3xl border border-zinc-800 shadow-2xl flex flex-col overflow-hidden text-zinc-100">
        {/* Modal Top Control Bar */}
        <div className="h-16 px-6 bg-[#0d0d12] border-b border-zinc-800 flex items-center justify-between shrink-0">
          {/* File Info */}
          <div className="flex items-center gap-3 min-w-0">
            <div className="w-10 h-10 rounded-xl bg-red-950/40 border border-red-800/40 flex items-center justify-center text-red-400 shrink-0">
              {activeDoc.type === "pdf" ? (
                <FileText className="w-5 h-5 text-red-400" />
              ) : activeDoc.type === "sheet" ? (
                <FileSpreadsheet className="w-5 h-5 text-emerald-400" />
              ) : activeDoc.type === "pptx" ? (
                <Presentation className="w-5 h-5 text-amber-400" />
              ) : (
                <FileCode className="w-5 h-5 text-red-400" />
              )}
            </div>
            <div className="min-w-0">
              <h3 className="font-bold text-sm text-white truncate tracking-tight">
                {activeDoc.filename}
              </h3>
              <p className="text-xs text-zinc-400 flex items-center gap-2 font-mono">
                <span>{activeDoc.size}</span>
                <span>·</span>
                <span className="text-emerald-400 flex items-center gap-1 font-semibold">
                  <ShieldCheck className="w-3.5 h-3.5" />
                  Air-Gap Signed
                </span>
              </p>
            </div>
          </div>

          {/* Device Mode Switcher (Phone / Tablet / Desktop) */}
          <div className="hidden md:flex items-center gap-1 bg-zinc-900 p-1 rounded-2xl border border-zinc-800">
            <button
              onClick={() => setDeviceMode("desktop")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                deviceMode === "desktop"
                  ? "bg-gradient-to-r from-red-600 to-red-700 text-white shadow-xs"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
              title="A4 Document Paper View"
            >
              <Monitor className="w-3.5 h-3.5" />
              <span>Document Paper</span>
            </button>
            <button
              onClick={() => setDeviceMode("tablet")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                deviceMode === "tablet"
                  ? "bg-gradient-to-r from-red-600 to-red-700 text-white shadow-xs"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
              title="Tablet Reader View"
            >
              <Tablet className="w-3.5 h-3.5" />
              <span>Tablet View</span>
            </button>
            <button
              onClick={() => setDeviceMode("phone")}
              className={`flex items-center gap-1.5 px-3 py-1.5 rounded-xl text-xs font-semibold transition-all cursor-pointer ${
                deviceMode === "phone"
                  ? "bg-gradient-to-r from-red-600 to-red-700 text-white shadow-xs"
                  : "text-zinc-400 hover:text-zinc-200"
              }`}
              title="Mobile Device Phone View"
            >
              <Smartphone className="w-3.5 h-3.5" />
              <span>Phone View</span>
            </button>
          </div>

          {/* Zoom & Page Navigation & Close */}
          <div className="flex items-center gap-2">
            {/* Zoom Controls */}
            {deviceMode === "desktop" && (
              <div className="hidden sm:flex items-center gap-1 bg-slate-800/80 px-2 py-1 rounded-xl border border-slate-700 text-xs">
                <button
                  onClick={() => handleZoom(-10)}
                  className="p-1 hover:text-white transition-colors cursor-pointer"
                  title="Zoom Out"
                >
                  <ZoomOut className="w-3.5 h-3.5 text-slate-400" />
                </button>
                <span className="px-1.5 font-mono text-slate-300 min-w-[40px] text-center">
                  {zoomLevel}%
                </span>
                <button
                  onClick={() => handleZoom(10)}
                  className="p-1 hover:text-white transition-colors cursor-pointer"
                  title="Zoom In"
                >
                  <ZoomIn className="w-3.5 h-3.5 text-slate-400" />
                </button>
              </div>
            )}

            {/* Pagination Controls */}
            {totalPages > 1 && (
              <div className="flex items-center gap-1 bg-slate-800/80 px-2 py-1 rounded-xl border border-slate-700 text-xs">
                <button
                  disabled={currentPage <= 1}
                  onClick={() => setCurrentPage((p) => Math.max(p - 1, 1))}
                  className="p-1 hover:text-white disabled:opacity-30 transition-colors cursor-pointer"
                >
                  <ChevronLeft className="w-3.5 h-3.5" />
                </button>
                <span className="px-1 text-slate-300 font-medium">
                  {currentPage} / {totalPages}
                </span>
                <button
                  disabled={currentPage >= totalPages}
                  onClick={() => setCurrentPage((p) => Math.min(p + 1, totalPages))}
                  className="p-1 hover:text-white disabled:opacity-30 transition-colors cursor-pointer"
                >
                  <ChevronRight className="w-3.5 h-3.5" />
                </button>
              </div>
            )}

            {/* Download Button */}
            <button
              onClick={() => onDownload && onDownload(activeDoc)}
              className="hidden sm:flex items-center gap-1.5 px-3 py-1.5 bg-slate-800 hover:bg-slate-700 text-slate-200 rounded-xl text-xs font-semibold border border-slate-700 transition-colors cursor-pointer"
              title="Download Document"
            >
              <Download className="w-3.5 h-3.5" />
              <span>Download</span>
            </button>

            {/* Close Modal Button */}
            <button
              onClick={onClose}
              className="w-8 h-8 rounded-xl bg-slate-800 hover:bg-rose-900/60 text-slate-400 hover:text-rose-400 flex items-center justify-center transition-colors cursor-pointer"
              title="Close Preview"
            >
              <X className="w-4 h-4" />
            </button>
          </div>
        </div>

        {/* Live Document Working Status Banner */}
        <div className="bg-[#09090b] border-b border-red-950/50 px-6 py-2.5 flex flex-col sm:flex-row sm:items-center justify-between gap-2.5 text-xs select-none">
          <div className="flex items-center gap-2.5">
            <span className="w-2.5 h-2.5 rounded-full bg-red-500 animate-ping shrink-0" />
            <span className="text-red-400 font-bold tracking-wide flex items-center gap-1.5 font-mono">
              <Activity className="w-3.5 h-3.5" />
              <span>ACTIVE PROCESSING IN-PROGRESS:</span>
            </span>
            <span className="text-zinc-400 font-medium">
              Being worked on by Agent Alpha (ITAR Sentinel) & RapidOCR Engine
            </span>
          </div>

          <div className="flex items-center gap-3">
            <div className="flex items-center gap-1.5 text-red-300 font-mono text-[11.5px]">
              <Sparkles className="w-3 h-3 text-red-400 animate-spin" />
              <span>Clause Verification: 84% complete</span>
            </div>
            <div className="w-28 h-2 bg-zinc-900 rounded-full overflow-hidden shrink-0 border border-zinc-800">
              <div className="h-full bg-gradient-to-r from-red-600 via-rose-500 to-amber-500 w-[84%] animate-pulse" />
            </div>
          </div>
        </div>

        {/* Preview Viewport Canvas */}
        <div className="flex-1 bg-slate-950 overflow-y-auto p-4 sm:p-8 flex justify-center items-start select-text relative">
          {/* Real-time laser scanning effect traversing across the viewport */}
          <div className="absolute top-0 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-cyan-400 to-transparent shadow-[0_0_12px_#22d3ee] animate-pulse pointer-events-none z-20" />
          {/* 1. MOBILE PHONE CONTAINER VIEW */}
          {deviceMode === "phone" && (
            <div className="w-[375px] max-w-full my-auto rounded-[48px] bg-slate-900 border-[10px] border-slate-800 shadow-[0_25px_60px_rgba(0,0,0,0.8)] overflow-hidden flex flex-col shrink-0 animate-in zoom-in-95">
              {/* Phone Notch & Status Bar */}
              <div className="h-9 bg-slate-900 px-6 flex items-center justify-between text-[11px] text-slate-400 shrink-0 select-none">
                <span className="font-semibold text-white">9:41</span>
                {/* Speaker Notch */}
                <div className="w-24 h-4 rounded-full bg-slate-950 flex items-center justify-center">
                  <div className="w-3 h-3 rounded-full bg-slate-800" />
                </div>
                <div className="flex items-center gap-1 text-[10px]">
                  <span>5G</span>
                  <span className="font-mono">100%</span>
                </div>
              </div>

              {/* Phone Document Viewport */}
              <div className="bg-white text-slate-900 p-5 space-y-4 max-h-[640px] overflow-y-auto">
                {/* Mobile Header Banner */}
                <div className="border-b border-slate-200 pb-3">
                  <div className="flex items-center justify-between text-[10px] text-slate-500 font-semibold uppercase tracking-wider mb-1">
                    <span>AstraSovereign Mobile Reader</span>
                    <span className="text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200">
                      AIR-GAP
                    </span>
                  </div>
                  <h1 className="text-base font-bold text-slate-900 leading-tight">
                    {activeDoc.title}
                  </h1>
                  <p className="text-[11px] text-slate-500 mt-1">
                    {activeDoc.author} · {activeDoc.date}
                  </p>
                </div>

                {/* Mobile Document Sections */}
                {activePageData?.sections.map((sec, idx) => (
                  <div key={idx} className="space-y-2">
                    {sec.heading && (
                      <h2 className="text-xs font-bold text-slate-800 uppercase tracking-wide">
                        {sec.heading}
                      </h2>
                    )}
                    <p className="text-xs text-slate-700 leading-relaxed font-sans">
                      {sec.content}
                    </p>

                    {sec.callout && (
                      <div className="p-3 rounded-xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-800 font-medium leading-relaxed">
                        {sec.callout.text}
                      </div>
                    )}

                    {sec.table && (
                      <div className="overflow-x-auto rounded-xl border border-slate-200 mt-2">
                        <table className="w-full text-left text-[11px]">
                          <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
                            <tr>
                              {sec.table.headers.map((h, i) => (
                                <th key={i} className="p-2 truncate">
                                  {h}
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 text-slate-800">
                            {sec.table.rows.map((r, ri) => (
                              <tr key={ri} className="hover:bg-slate-50/70">
                                {r.map((c, ci) => (
                                  <td key={ci} className="p-2 whitespace-nowrap font-medium">
                                    {c}
                                  </td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                ))}

                {/* Mobile Document Footer Signature Block */}
                <div className="pt-4 border-t border-slate-200 text-[10px] text-slate-500 space-y-1">
                  <div className="flex items-center justify-between">
                    <span className="font-semibold">SHA-256 Digest:</span>
                    <span className="font-mono text-[9px] text-slate-700 truncate w-36">
                      {activeDoc.hash.slice(0, 18)}...
                    </span>
                  </div>
                  <div className="text-center font-bold text-emerald-700 pt-1">
                    VERIFIED ON-PREMISE AIR-GAP ARTIFACT
                  </div>
                </div>
              </div>

              {/* Home Indicator Bar */}
              <div className="h-6 bg-slate-900 flex items-center justify-center shrink-0">
                <div className="w-32 h-1 rounded-full bg-slate-700" />
              </div>
            </div>
          )}

          {/* 2. TABLET CONTAINER VIEW */}
          {deviceMode === "tablet" && (
            <div className="w-[760px] max-w-full my-auto rounded-[36px] bg-slate-900 border-[12px] border-slate-800 shadow-2xl overflow-hidden flex flex-col shrink-0 animate-in zoom-in-95">
              <div className="h-8 bg-slate-900 px-6 flex items-center justify-between text-xs text-slate-400 shrink-0">
                <span className="font-semibold text-white">Sovereign Tablet View</span>
                <span className="font-mono text-emerald-400">Air-Gap Encrypted</span>
              </div>
              <div className="bg-white text-slate-900 p-8 space-y-6 max-h-[660px] overflow-y-auto">
                <div className="border-b border-slate-200 pb-4">
                  <span className="text-xs font-bold text-red-600 uppercase tracking-wider font-mono">
                    {activeDoc.department}
                  </span>
                  <h1 className="text-xl font-bold text-slate-900 mt-1">{activeDoc.title}</h1>
                  <p className="text-xs text-slate-500 mt-1">
                    Author: {activeDoc.author} · Date: {activeDoc.date}
                  </p>
                </div>

                {activePageData?.sections.map((sec, idx) => (
                  <div key={idx} className="space-y-3">
                    {sec.heading && (
                      <h2 className="text-sm font-bold text-slate-900 uppercase tracking-wide">
                        {sec.heading}
                      </h2>
                    )}
                    <p className="text-sm text-slate-700 leading-relaxed font-sans">{sec.content}</p>

                    {sec.callout && (
                      <div className="p-4 rounded-xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-800 font-medium">
                        {sec.callout.text}
                      </div>
                    )}

                    {sec.table && (
                      <div className="overflow-x-auto rounded-xl border border-slate-200">
                        <table className="w-full text-left text-xs">
                          <thead className="bg-slate-50 text-slate-600 font-semibold border-b border-slate-200">
                            <tr>
                              {sec.table.headers.map((h, i) => (
                                <th key={i} className="p-3">
                                  {h}
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 text-slate-800">
                            {sec.table.rows.map((r, ri) => (
                              <tr key={ri} className="hover:bg-slate-50">
                                {r.map((c, ci) => (
                                  <td key={ci} className="p-3 font-medium">
                                    {c}
                                  </td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* 3. DESKTOP FORMAL A4 PAPER VIEW */}
          {deviceMode === "desktop" && (
            <div
              style={{ transform: `scale(${zoomLevel / 100})`, transformOrigin: "top center" }}
              className="w-[820px] max-w-full bg-white text-slate-900 shadow-2xl rounded-xl border border-slate-200/90 transition-transform duration-200 shrink-0 p-12 space-y-8 min-h-[960px] flex flex-col justify-between"
            >
              {/* Formal Letterhead */}
              <div className="space-y-4 border-b-2 border-slate-900 pb-6">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-3">
                    <div className="w-10 h-10 rounded-xl bg-gradient-to-tr from-red-600 to-red-700 flex items-center justify-center text-white font-black text-sm shadow-[0_0_12px_rgba(239,68,68,0.3)]">
                      AS
                    </div>
                    <div>
                      <h2 className="text-lg font-black text-slate-900 tracking-tight leading-tight">
                        ASTRASOVEREIGN WORKBENCH
                      </h2>
                      <p className="text-[11px] font-semibold uppercase tracking-wider text-slate-500 font-mono">
                        Air-Gapped Sovereign Intelligence Protocol
                      </p>
                    </div>
                  </div>

                  <div className="text-right">
                    <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold">
                      <ShieldCheck className="w-3.5 h-3.5" />
                      <span>OFFICIAL CLEARANCE</span>
                    </div>
                    <p className="text-[11px] text-slate-400 mt-1 font-mono">
                      REF: {activeDoc.id.toUpperCase()}
                    </p>
                  </div>
                </div>

                <div className="pt-2">
                  <h1 className="text-2xl font-black text-slate-900 tracking-tight leading-snug">
                    {activeDoc.title}
                  </h1>
                </div>

                {/* Metadata Row */}
                <div className="grid grid-cols-3 gap-4 pt-2 text-xs text-slate-600 bg-slate-50 p-3.5 rounded-xl border border-slate-200/80">
                  <div>
                    <span className="font-bold text-slate-900 block">Department:</span>
                    <span>{activeDoc.department}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-900 block">Author / Officer:</span>
                    <span>{activeDoc.author}</span>
                  </div>
                  <div>
                    <span className="font-bold text-slate-900 block">Date of Verification:</span>
                    <span>{activeDoc.date}</span>
                  </div>
                </div>
              </div>

              {/* Live In-Flight Working Annotation */}
              <div className="p-4 rounded-2xl bg-red-950/40 border border-red-800/60 text-xs space-y-1.5 animate-in fade-in select-text shadow-2xs">
                <div className="flex items-center justify-between text-red-200 font-bold font-mono">
                  <span className="flex items-center gap-2">
                    <Sparkles className="w-4 h-4 text-red-400 animate-spin" />
                    <span>Live In-Flight Annotation by Agent Alpha (ITAR Sentinel)</span>
                  </span>
                  <span className="text-[10px] font-mono text-red-300 bg-red-900/60 border border-red-700/60 px-2 py-0.5 rounded-full font-bold">
                    IN-PROGRESS · 84% COMPLETE
                  </span>
                </div>
                <p className="text-zinc-300 leading-relaxed font-sans text-xs">
                  Automated clause extraction active. 14 vendor contractual agreements verified against ITAR Category VIII/XII regulations. Loopback SHA-256 verification hash generated on PCIe NVLink.
                </p>
              </div>

              {/* Document Body Sections */}
              <div className="space-y-6 flex-1">
                {activePageData?.sections.map((sec, idx) => (
                  <div key={idx} className="space-y-3">
                    {sec.heading && (
                      <h3 className="text-base font-bold text-slate-900 tracking-tight border-b border-slate-200 pb-1">
                        {sec.heading}
                      </h3>
                    )}
                    <p className="text-sm text-slate-800 leading-relaxed font-sans">{sec.content}</p>

                    {sec.callout && (
                      <div
                        className={`p-4 rounded-xl border text-xs font-semibold leading-relaxed ${
                          sec.callout.type === "success"
                            ? "bg-emerald-50 border-emerald-200 text-emerald-800"
                            : "bg-amber-50 border-amber-200 text-amber-900"
                        }`}
                      >
                        {sec.callout.text}
                      </div>
                    )}

                    {sec.table && (
                      <div className="overflow-x-auto rounded-xl border border-slate-200 my-3">
                        <table className="w-full text-left text-xs">
                          <thead className="bg-slate-100/80 text-slate-700 font-bold border-b border-slate-200">
                            <tr>
                              {sec.table.headers.map((h, i) => (
                                <th key={i} className="p-3.5">
                                  {h}
                                </th>
                              ))}
                            </tr>
                          </thead>
                          <tbody className="divide-y divide-slate-100 text-slate-800">
                            {sec.table.rows.map((r, ri) => (
                              <tr key={ri} className="hover:bg-slate-50 transition-colors">
                                {r.map((c, ci) => (
                                  <td key={ci} className="p-3.5 font-medium">
                                    {c}
                                  </td>
                                ))}
                              </tr>
                            ))}
                          </tbody>
                        </table>
                      </div>
                    )}
                  </div>
                ))}
              </div>

              {/* Official Sign-Off Footer & SHA-256 Ledger Stamp */}
              <div className="pt-6 border-t-2 border-slate-900 space-y-4">
                <div className="grid grid-cols-2 gap-8 text-xs text-slate-600">
                  <div className="space-y-2">
                    <span className="font-bold text-slate-900 block uppercase tracking-wider text-[11px]">
                      Cryptographic Ledger Verification
                    </span>
                    <div className="p-2.5 rounded-lg bg-slate-50 border border-slate-200 font-mono text-[10.5px] text-slate-700 break-all">
                      {activeDoc.hash}
                    </div>
                    <p className="text-[10px] text-slate-400">
                      Generated strictly on local CPU/GPU hardware without cloud telemetry.
                    </p>
                  </div>

                  <div className="flex flex-col justify-end items-end text-right space-y-2">
                    <div className="w-48 border-b border-slate-400 pb-1 text-center font-serif italic text-slate-800 text-sm">
                      user-001 (Officer Lead)
                    </div>
                    <span className="text-[11px] font-bold text-slate-700">
                      Authorized Sovereign Signature
                    </span>
                    <span className="text-[10px] text-slate-400">
                      Clearance Level L4 · Security Stamp Valid
                    </span>
                  </div>
                </div>

                <div className="flex items-center justify-between text-[11px] text-slate-400 pt-2 border-t border-slate-100">
                  <span>AstraSovereign System Document # {activeDoc.id}</span>
                  <span>
                    Page {currentPage} of {totalPages}
                  </span>
                  <span>100% On-Premise Air-Gap</span>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
