"""HTTP API: job retrieval, listing, and cancellation.

Ownership is enforced by the JobManager; these routes only translate errors.
Generated artifacts are exposed through the job detail and a secure download
endpoint — no generic filesystem access is exposed.
"""

import logging
from pathlib import Path
from typing import Optional

from fastapi import APIRouter, Depends, HTTPException, Query, Request, status
from fastapi.responses import FileResponse

from app.api.deps import get_user_id
from app.schemas.artifact import ArtifactSummary
from app.schemas.job import Job, JobStatus, JobSummary
from app.services.job_manager import JobNotFoundError, JobPermissionError, JobStateError

logger = logging.getLogger("app.api.jobs")

router = APIRouter(prefix="/api/jobs", tags=["jobs"])

_WORD_MEDIA_TYPE = "application/vnd.openxmlformats-officedocument.wordprocessingml.document"
_ARTIFACT_MEDIA_TYPES = {
    "word": _WORD_MEDIA_TYPE,
}


async def _attach_artifacts(request: Request, job: Job) -> Job:
    artifact_store = request.app.state.artifact_store
    artifacts = []
    try:
        artifacts = await artifact_store.list_for_job(job.job_id)
    except Exception:  # artifact listing must never break job retrieval
        logger.exception(
            "job_artifact_list_error",
            extra={"event": "job_artifact_list_error", "job_id": job.job_id},
        )
    job.artifacts = [ArtifactSummary.from_artifact(a) for a in artifacts]
    return job


@router.get("/{job_id}", response_model=Job)
async def get_job(
    job_id: str,
    request: Request,
    user_id: str = Depends(get_user_id),
) -> Job:
    """Return a job's full detail (with its artifacts), but only to its owner."""
    manager = request.app.state.job_manager
    try:
        job = await manager.get_job(user_id, job_id)
    except JobNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "job_not_found", "message": "Job not found."},
        )
    except JobPermissionError:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={"error": "forbidden", "message": "You do not have access to this job."},
        )
    return await _attach_artifacts(request, job)


@router.get("/{job_id}/artifacts/{artifact_id}", response_class=FileResponse)
async def download_artifact(
    job_id: str,
    artifact_id: str,
    request: Request,
    user_id: str = Depends(get_user_id),
) -> FileResponse:
    """Securely download an artifact generated by one of the caller's jobs.

    Ownership and workspace containment are verified before any file is served.
    """
    manager = request.app.state.job_manager
    try:
        await manager.get_job(user_id, job_id)
    except JobNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "job_not_found", "message": "Job not found."},
        )
    except JobPermissionError:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={"error": "forbidden", "message": "You do not have access to this job."},
        )

    artifact_store = request.app.state.artifact_store
    artifact = await artifact_store.get(artifact_id)
    if artifact is None or artifact.job_id != job_id or artifact.user_id != user_id:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "artifact_not_found", "message": "Artifact not found."},
        )

    workspace = request.app.state.workspace_manager.workspace_path(user_id, job_id)
    path = Path(artifact.path).resolve()
    if not path.is_relative_to(workspace.resolve()):
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "artifact_not_found", "message": "Artifact not found."},
        )
    if not path.is_file():
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "artifact_not_found", "message": "Artifact file is missing."},
        )

    media_type = _ARTIFACT_MEDIA_TYPES.get(artifact.type, "application/octet-stream")
    return FileResponse(
        path,
        filename=artifact.filename,
        media_type=media_type,
        content_disposition_type="attachment",
    )


@router.get("", response_model=list[JobSummary])
async def list_jobs(
    request: Request,
    user_id: str = Depends(get_user_id),
    job_status: Optional[JobStatus] = Query(default=None, alias="status"),
    limit: int = Query(default=50, ge=1, le=200),
    offset: int = Query(default=0, ge=0),
) -> list[JobSummary]:
    """List the caller's own jobs (newest first). Never returns other users' jobs."""
    manager = request.app.state.job_manager
    jobs = await manager.list_jobs(
        user_id,
        status=job_status,
        limit=limit,
        offset=offset,
    )
    return [JobSummary.from_job(job) for job in jobs]


@router.delete("/{job_id}", response_model=Job)
async def cancel_job(
    job_id: str,
    request: Request,
    user_id: str = Depends(get_user_id),
) -> Job:
    """Cancel a queued job. Running or terminal jobs cannot be cancelled."""
    manager = request.app.state.job_manager
    try:
        return await manager.cancel_job(user_id, job_id)
    except JobNotFoundError:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail={"error": "job_not_found", "message": "Job not found."},
        )
    except JobPermissionError:
        raise HTTPException(
            status_code=status.HTTP_403_FORBIDDEN,
            detail={"error": "forbidden", "message": "You do not have access to this job."},
        )
    except JobStateError as exc:
        raise HTTPException(
            status_code=status.HTTP_409_CONFLICT,
            detail={"error": "invalid_state", "message": str(exc)},
        )
